In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
np.arange(1,51,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [5]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int32')

In [8]:
b.size

6

In [9]:
b.itemsize

4

In [10]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
arr1 = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])

arr2 = np.array([[9,8,7],
       [6,5,4],
       [3,2,1]])

In [14]:
arr3 = arr2-arr1
arr3

array([[ 8,  6,  4],
       [ 2,  0, -2],
       [-4, -6, -8]])

In [15]:
arr3 = arr2 + arr1
arr3

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
arr3 = arr2 / arr1
arr3

array([[9.        , 4.        , 2.33333333],
       [1.5       , 1.        , 0.66666667],
       [0.42857143, 0.25      , 0.11111111]])

In [17]:
arr3 = arr2 * arr1
arr3

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [18]:
arr3 = arr2 @ arr1
arr3

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr2.transpose()

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [21]:
a= np.array([[1,2],
            [3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
a = np.arange(30)
b = a.reshape((2, -1, 3)) # -1 means "whatever is needed"
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [23]:
rng = np.random.default_rng(0)
rng.random(3)


array([0.63696169, 0.26978671, 0.04097352])

In [24]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, indices_list = np.unique(a, return_index=True)
unique_values, indices_list

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [25]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [26]:
arr_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [28]:
x = np.arange(30).reshape(2,3,5)
x>20,x

(array([[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],
 
        [[False, False, False, False, False],
         [False,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]]),
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]))

In [29]:
 x = np.arange(12).reshape((3,4))
print(x)
x.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [30]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [31]:
x = np.mat([[1, 2], [3, 4]])
print (x)
x**2

[[1 2]
 [3 4]]


matrix([[ 7, 10],
        [15, 22]])

In [32]:
x.min()

1

In [33]:
x.mean()

2.5

In [34]:
a = np.array([10,5,11,4,7,1])
a.sort()
a

array([ 1,  4,  5,  7, 10, 11])

In [35]:
a.max()

11

In [36]:
c=np.arange(18).reshape(2,3,3)
np.vsplit(c,2)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]),
 array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])]

In [37]:
np.hsplit(c,3) 

[array([[[ 0,  1,  2]],
 
        [[ 9, 10, 11]]]),
 array([[[ 3,  4,  5]],
 
        [[12, 13, 14]]]),
 array([[[ 6,  7,  8]],
 
        [[15, 16, 17]]])]

In [38]:
c[ : :-1] 

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [39]:
a= np.arange(6)
a[ : :-1] 

array([5, 4, 3, 2, 1, 0])

In [40]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [41]:
np.random.random((3,3))

array([[0.48733535, 0.12693175, 0.15292079],
       [0.44962404, 0.26848276, 0.06720345],
       [0.65794742, 0.22600466, 0.48216477]])

In [42]:
np.empty((3,2)) 

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313]])

In [43]:
 c.astype(float) 

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]]])

In [44]:
c.std()

5.188127472091127

In [45]:
c.cumsum(axis=1)

array([[[ 0,  1,  2],
        [ 3,  5,  7],
        [ 9, 12, 15]],

       [[ 9, 10, 11],
        [21, 23, 25],
        [36, 39, 42]]], dtype=int32)

In [46]:
h = c.copy() #deep copy
h

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [47]:
np.sin(c) 
np.cos(c) 

array([[[ 1.        ,  0.54030231, -0.41614684],
        [-0.9899925 , -0.65364362,  0.28366219],
        [ 0.96017029,  0.75390225, -0.14550003]],

       [[-0.91113026, -0.83907153,  0.0044257 ],
        [ 0.84385396,  0.90744678,  0.13673722],
        [-0.75968791, -0.95765948, -0.27516334]]])

In [48]:
np.cos(c) 

array([[[ 1.        ,  0.54030231, -0.41614684],
        [-0.9899925 , -0.65364362,  0.28366219],
        [ 0.96017029,  0.75390225, -0.14550003]],

       [[-0.91113026, -0.83907153,  0.0044257 ],
        [ 0.84385396,  0.90744678,  0.13673722],
        [-0.75968791, -0.95765948, -0.27516334]]])

In [49]:
np.sqrt(c) 

array([[[0.        , 1.        , 1.41421356],
        [1.73205081, 2.        , 2.23606798],
        [2.44948974, 2.64575131, 2.82842712]],

       [[3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739],
        [3.87298335, 4.        , 4.12310563]]])

In [50]:
np.exp(c) 


array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
        [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]],

       [[8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
        [3.26901737e+06, 8.88611052e+06, 2.41549528e+07]]])

In [51]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
